MODEL:
  TYPE: swinv2
  NAME: simmim_pretrain
  DROP_PATH_RATE: 0.2
  SWINV2:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 12
DATA:
  BATCH_SIZE: 4
  IMG_SIZE: 192
  MASK_PATCH_SIZE: 4
  MASK_RATIO: 0.5
  NUM_WORKERS: 16
TRAIN:
  EPOCHS: 400
  WARMUP_EPOCHS: 10
  BASE_LR: 1e-2
  MIN_LR: 1e-6
  WARMUP_LR: 1e-6
  WEIGHT_DECAY: 0.05
  OPTIMIZER:
    NAME: adamw
    BETA_1: 0.85
    BETA_2: 0.95
  ACCUMULATION_STEPS: 4
  LR_SCHEDULER:
    NAME: 'plateau'
    PATIENCE_T: 20
    THRESHOLD: 1e-2
    COOLDOWN_T: 0
    MODE: 'min'
    EARLY_STOP: True
PRINT_FREQ: 20
SAVE_FREQ: 50
TAG: simmim_pretrain__swinv2_base