MODEL:
  TYPE: swinv2
  NAME: simmim_pretrain
  DROP_PATH_RATE: 0.1
  SIMMIM:
    NORM_TARGET:
      ENABLE: True
      PATCH_SIZE: 71
  SWINV2:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 16
DATA:
  BATCH_SIZE: 16
  IMG_SIZE: 256
  MASK_PATCH_SIZE: 16
  MASK_RATIO: 0.2
TRAIN:
  EPOCHS: 400
  WARMUP_EPOCHS: 10
  BASE_LR: 1e-1 # 1e-0
  MIN_LR: 1e-6
  WARMUP_LR: 1e-5
  WEIGHT_DECAY: 0.05
  LR_SCHEDULER:
    NAME: 'plateau'
    PATIENCE_T: 10
    THRESHOLD: 1e-2
    COOLDOWN_T: 0
    MODE: 'min'
    EARLY_STOP: True
PRINT_FREQ: 100
SAVE_FREQ: 50
TAG: simmim_pretrain__swinv2_base__img256_window16__400ep